Repository BobAnkh/THUBurrow, pull requests merged in 2021-12, with the labels that each got.

#28 feat(post): add like and favorites in post list and post details page
  frontend/components/login-form.tsx
  frontend/components/post-list.tsx
  frontend/components/reply-list.tsx
  frontend/pages/burrow/[bid].tsx
  frontend/pages/post/[pid].tsx
Labels: enhancement

#30 fix(frontend): modify the axios default configuration to support cross-domain requests
  frontend/pages/home.tsx
Labels: bug

#20 feat(burrow): implement core concept burrow
  .github/workflows/backend-build-test.yml
  backend/Cargo.lock
  backend/Cargo.toml
  backend/Dockerfile
  backend/README.md
  backend/Rocket.toml
  backend/docker-compose-dev.yml
  backend/docker-compose.yml
  backend/docker-entrypoint.sh
  backend/src/bin/consumer/main.rs
  backend/src/lib.rs
  backend/src/main.rs
  backend/src/pgdb/burrow.rs
  backend/src/pgdb/content_post.rs
  backend/src/pgdb/content_reply.rs
  backend/src/pgdb/mod.rs
  backend/src/pgdb/prelude.rs
  backend/src/pgdb/user_collection.rs
  backend/src/pgdb/user_follow.rs
  backend/src/pgdb/user_like.rs
  backend/src/pgdb/user_status.rs
  backend/src/pool.rs
  backend/src/req/burrow.rs
  backend/src/req/content.rs
  backend/src/req/mod.rs
  backend/src/req/pulsar.rs
  backend/src/req/user.rs
  backend/src/routes/burrow.rs
  backend/src/routes/content.rs
  backend/src/routes/mod.rs
  backend/src/routes/sample.rs
  backend/src/routes/storage.rs
  backend/src/routes/trending.rs
  backend/src/routes/user.rs
  backend/src/setup.rs
  backend/src/utils/auth.rs
  backend/src/utils/burrow_valid.rs
  backend/src/utils/email.rs
  backend/src/utils/mod.rs
  backend/tests/common/mod.rs
  backend/tests/lib.rs
Labels: enhancement

#33 improvement(login):reconsitution login and findbackpassword,delete and move some css
  frontend/components/findback-password.tsx
  frontend/components/header/title.module.css
  frontend/components/login-form.tsx
  frontend/components/register.tsx
  frontend/pages/login.tsx
  frontend/styles/register.module.css
  frontend/styles/standard-form-row.module.css
Labels: enhancement

#36 Feature(revise regist): revise register.tsx and update the burrow folder
  frontend/components/register.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/burrow/[bid].tsx
  frontend/pages/burrow/burrow.module.css
  frontend/styles/register.module.css
  frontend/yarn.lock
Labels: enhancement

#40 feat(page): modify the page
  frontend/components/post-list.tsx
  frontend/components/reply-list.tsx
  frontend/pages/home.tsx
  frontend/pages/post/[pid].tsx
  frontend/pages/profile.tsx
  frontend/pages/trending.tsx
Labels: enhancement

#46 fix(register): change url
  frontend/components/register.tsx
  frontend/models/search/data.d.tsx
  frontend/pages/searchpage.tsx
Labels: bug

#49 Fix(search):Rewrite the search page according to the interface
  frontend/.env
  frontend/components/findback-password.tsx
  frontend/components/login-form.tsx
  frontend/components/pbListContent/post-or-burrow-list.tsx
  frontend/components/register.tsx
  frontend/models/search/data.d.tsx
  frontend/pages/searchpage.tsx
  frontend/styles/search.module.css
Labels: enhancement

#50 Fix(burrowpage): fix bugs and make the function of counting down work correctly
  frontend/components/register.tsx
  frontend/pages/burrow/[bid].tsx
Labels: bug

#52 feat(create): add create page
  frontend/.editorconfig
  frontend/components/header/header.tsx
  frontend/components/post-list.tsx
  frontend/components/register.tsx
  frontend/components/reply-list.tsx
  frontend/package.json
  frontend/pages/burrow/[bid].tsx
  frontend/pages/create.tsx
  frontend/pages/home.tsx
  frontend/pages/post/[pid].tsx
  frontend/pages/profile.tsx
  frontend/pages/trending.tsx
  frontend/yarn.lock
Labels: enhancement

#53 Feature(abandoned): add abandoned page and fix several bugs
  frontend/components/register.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/burrow/[bid].tsx
  frontend/yarn.lock
Labels: enhancement

#59 feat(retrieve-password):retrieve-password
  frontend/components/findback-password.tsx
Labels: enhancement

#58 feat(post): add function of modify reply
  frontend/.env
  frontend/components/post-list.tsx
  frontend/components/reply-list.tsx
  frontend/pages/burrow/[bid].tsx
  frontend/pages/home.tsx
  frontend/pages/post/[pid].tsx
  frontend/pages/profile.tsx
  frontend/pages/trending.tsx
Labels: enhancement

#45 refactor(backend): reorganize interfaces and file structure
  .github/workflows/backend-docs.yml
  .github/workflows/backend-lint.yml
  .github/workflows/backend-test.yml
  .github/workflows/build-image.yml
  .gitignore
  backend/.env.sample
  backend/Cargo.lock
  backend/Cargo.toml
  backend/Dockerfile
  backend/backend-service.yml
  backend/benches/backend_bench.rs
  backend/conf/log4rs.yml
  backend/docker-compose-dev.yml
  backend/docker-compose-pulsar.yml
  backend/docker-compose.yml
  backend/docker-entrypoint.sh
  backend/src/bin/consumer/main.rs
  backend/src/bin/task_executor/main.rs
  backend/src/config/email.rs
  backend/src/config/mod.rs
  backend/src/config/mq.rs
  backend/src/config/user.rs
  backend/src/db/user.rs
  backend/src/lib.rs
  backend/src/models/burrow.rs
  backend/src/models/content.rs
  backend/src/models/error.rs
  backend/src/models/mod.rs
  backend/src/models/pulsar.rs
  backend/src/models/search.rs
  backend/src/models/storage.rs
  backend/src/models/user.rs
  backend/src/pgdb/burrow.rs
  backend/src/pool.rs
  backend/src/req/burrow.rs
  backend/src/req/content.rs
  backend/src/req/pulsar.rs
  backend/src/routes/burrow.rs
  backend/src/routes/content.rs
  backend/src/routes/mod.rs
  backend/src/routes/sample.rs
  backend/src/routes/search.rs
  backend/src/routes/storage.rs
  backend/src/routes/trending.rs
  backend/src/routes/user.rs
  backend/src/setup.rs
  backend/src/utils/auth.rs
  backend/src/utils/dedup.rs
  backend/src/utils/email.rs
  backend/src/utils/id_gen.rs
  backend/src/utils/mod.rs
  backend/src/utils/mq.rs
  backend/tests/common/mod.rs
  backend/tests/lib.rs
Labels: enhancement

#61 Fix(register problem): encrypt the passwords
  frontend/.env
  frontend/components/register.tsx
Labels: bug

#67 feat(user): add logout
  frontend/components/header/header.tsx
  frontend/components/post-list.tsx
  frontend/components/search/search-burrowid.tsx
  frontend/components/search/search-post.tsx
  frontend/pages/create.tsx
  frontend/pages/home.tsx
  frontend/pages/post/[pid].tsx
Labels: enhancement

#69 fix(post): update the url
  frontend/components/reply-list.tsx
  frontend/pages/create.tsx
  frontend/pages/home.tsx
  frontend/pages/post/[pid].tsx
Labels: bug

#70 feat(section): update the section
  frontend/pages/burrow/[bid].tsx
  frontend/pages/create.tsx
  frontend/pages/home.tsx
  frontend/pages/post/[pid].tsx
  frontend/pages/trending.tsx
Labels: enhancement

#71 fix(register error): fix the error of verifying password and sending email verification code
  frontend/components/register.tsx
  frontend/pages/burrow/[bid].tsx
Labels: bug

#73 (fix/search):Delete the search id method, directly jump to the corresponding url
  frontend/components/login-form.tsx
  frontend/components/search/search-burrow.tsx
  frontend/components/search/search-burrowid.tsx
  frontend/components/search/search-post.tsx
  frontend/components/search/search-postid.tsx
  frontend/components/search/search-reply.tsx
  frontend/pages/searchpage.tsx
Labels: bug

#78 feat(post): add update and delete post
  frontend/components/markdown/markdown.tsx
  frontend/components/post-list.tsx
  frontend/components/register.tsx
  frontend/components/reply-list.tsx
  frontend/package.json
  frontend/pages/create.tsx
  frontend/pages/post/[pid].tsx
  frontend/pages/profile.tsx
  frontend/styles/markdown.module.css
  frontend/yarn.lock
Labels: enhancement

#84 feat(upload): add upload image(draft)
  frontend/pages/test.tsx
Labels: enhancement

#85 Feature(upload)
  frontend/pages/test.tsx
Labels: bug, enhancement

#80 fix(search):change keyword to keywords,deactivateLike to DeactivateLike
  frontend/components/post-list.tsx
  frontend/components/search/search-burrow.tsx
  frontend/pages/burrow/[bid].tsx
  frontend/pages/post/[pid].tsx
  frontend/pages/searchpage.tsx
Labels: bug

#86 fix(add new email suffix): add new email suffix and revise the font
  frontend/components/findback-password.tsx
  frontend/components/post-list.tsx
  frontend/components/register.tsx
  frontend/pages/burrow/[bid].tsx
  frontend/pages/burrow/burrow.module.css
Labels: bug

#87 fix(post): modify display like and collection logic
  frontend/components/post-list.tsx
  frontend/pages/post/[pid].tsx
Labels: bug

#91 (fix/search):update url,add show reply number
  frontend/components/login-form.tsx
  frontend/components/search/search-burrow.tsx
  frontend/components/search/search-post.tsx
  frontend/components/search/search-reply.tsx
  frontend/pages/searchpage.tsx
Labels: bug

#94 (fix)search:remove {} in url
  frontend/components/search/search-burrow.tsx
  frontend/components/search/search-post.tsx
  frontend/components/search/search-reply.tsx
  frontend/pages/searchpage.tsx
Labels: bug

#95 fix(section): set limit on selecting tag and section
  frontend/components/register.tsx
  frontend/pages/create.tsx
  frontend/styles/register.module.css
Labels: bug

#97 feat(upload): add upload image to post
  frontend/components/storage/image-upload.tsx
  frontend/pages/create.tsx
Labels: enhancement

#98 fix(post):update api
  frontend/pages/burrow/[bid].tsx
  frontend/pages/post/[pid].tsx
Labels: bug

#105 fix(bug): post_id
  frontend/components/post-list.tsx
  frontend/pages/create.tsx
Labels: bug

#108 fix(post):add post-id
  frontend/pages/create.tsx
  frontend/pages/post/[pid].tsx
Labels: bug

#110 feat(addattention):add attention in burrow page
  frontend/pages/burrow/[bid].tsx
Labels: enhancement

#111 fix(search):contend have html language
  frontend/components/search/search-reply.tsx
Labels: bug

#117 fix(deserted): check the users if they are the host
  frontend/pages/burrow/[bid].tsx
Labels: bug

#120 fix(burrow page):click good
  frontend/pages/burrow/[bid].tsx
Labels: bug

#41 feat(frontend): add frontend v1.0.0
  .github/workflows/frontend-build-test.yml
  .gitignore
  frontend/.editorconfig
  frontend/.env
  frontend/.eslintrc.json
  frontend/.prettierrc.json
  frontend/README.md
  frontend/components/findback-password.tsx
  frontend/components/header/header.tsx
  frontend/components/index.ts
  frontend/components/login-form.tsx
  frontend/components/markdown/markdown.tsx
  frontend/components/post-list.tsx
  frontend/components/register.tsx
  frontend/components/reply-list.tsx
  frontend/components/search/search-burrow.tsx
  frontend/components/search/search-post.tsx
  frontend/components/search/search-reply.tsx
  frontend/components/storage/image-upload.tsx
  frontend/config.json
  frontend/models/search/data.d.tsx
  frontend/next-env.d.ts
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/404.tsx
  frontend/pages/_app.tsx
  frontend/pages/api/hello.ts
  frontend/pages/burrow/[bid].tsx
  frontend/pages/burrow/burrow.module.css
  frontend/pages/change-password.tsx
  frontend/pages/create.tsx
  frontend/pages/home.tsx
  frontend/pages/index.tsx
  frontend/pages/login.tsx
  frontend/pages/post/[pid].tsx
  frontend/pages/profile.tsx
  frontend/pages/searchpage.tsx
  frontend/pages/trending.tsx
  frontend/public/favicon.ico
  frontend/public/vercel.svg
  frontend/styles/Home.module.css
  frontend/styles/globals.css
  frontend/styles/markdown.module.css
  frontend/styles/pb-list.module.css
  frontend/styles/profile.module.css
  frontend/styles/register.module.css
  frontend/styles/search.module.css
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: enhancement

#125 fix(attention):add ! to fix the bug
  frontend/pages/burrow/[bid].tsx
Labels: bug
